CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `email` varchar(45) NOT NULL,
  `phone` varchar(45) NOT NULL,
  `coc` varchar(45) NOT NULL,
  `certificate_of_competence` date NULL,
  `covid_19` date NULL,
  `fitness` date NULL,
  `yellowF` date NULL,
  `PSSR` date NULL,
  `PSSRD` varchar(255) NULL,
  `covid_19D` varchar(255) NULL,
  `fitnessD` varchar(255) NULL,
  `SURVIVAL` date NULL,
  `FFB` date NULL,
  `ADV` date NULL,
  `elementary` date NULL,
  `MAMS` date NULL,
  `FRC` date NULL,
  `medical_first` date NULL,
  `medical_care` date NULL,
  `GMDSS` date NULL,
  `RADAR` date NULL,
  `ARPA` date NULL,
  `arpa_btw` date NULL,
  `ecdis_gen` date NULL,
  `SSO` date NULL,
  `leadership_managerial` date NULL,
  `high_voltage` date NULL,
  `leader_teamwork_engine` date NULL,
  `leader_teamwork_deck` date NULL,
  `security_awa` date NULL,
  `security_duties` date NULL,
  `basic_saf_fam` date NULL,
  `security_related_fam` date NULL,
  `ecdis_specific` date NULL,
  `yellowFD` varchar(255) NULL,
  `SURVD` varchar(255) NULL,
  `FFBD` varchar(255) NULL,
  `ADVD` varchar(255) NULL,
  `elementaryD` varchar(255) NULL,
  `MAMSD` varchar(255) NULL,
  `FRCD` varchar(255) NULL,
  `medical_firstD` varchar(255) NULL,
  `medical_careD` varchar(255) NULL,
  `GMDSSD` varchar(255) NULL,
  `RADARD` varchar(255) NULL,
  `ARPAD` varchar(255) NULL,
  `arpa_btwD` varchar(255) NULL,
  `ecdis_genD` varchar(255) NULL,
  `SSOD` varchar(255) NULL,
  `leadership_managerialD` varchar(255) NULL,
  `high_voltageD` varchar(255) NULL,
  `leader_teamwork_engineD` varchar(255) NULL,
  `leader_teamwork_deckD` varchar(255) NULL,
  `security_awaD` varchar(255) NULL,
  `security_dutiesD` varchar(255) NULL,
  `basic_saf_famD` varchar(255) NULL,
  `security_related_famD` varchar(255) NULL,
  `ecdis_specificD` varchar(255) NULL,
  `user_id` varchar(11) NOT NULL,
  `status` varchar(11) NOT NULL 'active'
) ENGINE=InnoDB CHARSET=latin1;
